<a href="https://colab.research.google.com/github/Kahkashan2708/Pytorch-code/blob/main/NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import torch
import torch.nn as nn

In [56]:
# Model
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [57]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model
model(features)    # model.forward(features)

tensor([[0.4144],
        [0.4187],
        [0.3953],
        [0.3813],
        [0.4239],
        [0.4697],
        [0.4167],
        [0.4075],
        [0.4002],
        [0.3886]], grad_fn=<SigmoidBackward0>)

In [58]:
model.linear.weight

Parameter containing:
tensor([[-0.1158, -0.3139, -0.3534, -0.2881, -0.1520]], requires_grad=True)

In [59]:
model.linear.bias

Parameter containing:
tensor([0.3275], requires_grad=True)

In [60]:
! pip install torchinfo

In [61]:
from torchinfo import summary
summary(model, inpur_size=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

---

In [62]:
# Model
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [63]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model
model(features)

tensor([[0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077]], grad_fn=<SigmoidBackward0>)

In [64]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2622, -0.2283,  0.4065, -0.4420, -0.3278],
        [-0.4357,  0.0228, -0.1094,  0.1190, -0.2577],
        [-0.0964, -0.3835, -0.2896, -0.4331,  0.0149]], requires_grad=True)

In [65]:
model.linear2.weight

Parameter containing:
tensor([[-0.1398, -0.2090, -0.5143]], requires_grad=True)

In [66]:
from torchinfo import summary
summary(model, inpur_size=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

Can we simplify forward pass?

Yes,We will use sequential containers

In [67]:
# Model
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(nn.Linear(num_features, 3),
                                nn.ReLU(),
                                nn.Linear(3,1),
                                nn.Sigmoid() )

  def forward(self, features):
    out = self.network(features)
    return out

---
---

In [68]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [69]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [70]:
df.shape

(569, 33)

In [71]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [72]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

**Train-test Split**

In [73]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

**Scaling**

In [74]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**Label Encoder**

In [75]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

**Numpy Arrays to pytorch Tensors**

In [76]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [77]:
X_train_tensor

tensor([[ 0.7247, -0.2390,  0.6551,  ..., -0.3327, -0.7877, -1.0234],
        [-0.1551, -1.5658, -0.2385,  ..., -1.4396, -0.9937, -1.1751],
        [-0.0378, -0.0131, -0.1086,  ..., -0.4885, -0.8494, -0.4023],
        ...,
        [ 0.6544,  0.6147,  0.6936,  ..., -0.1170, -0.2329, -0.2106],
        [-0.3134, -0.2390, -0.3030,  ..., -0.7354,  0.5311, -0.5972],
        [ 1.4873,  1.6633,  1.6167,  ...,  1.1544, -0.9224,  0.4741]],
       dtype=torch.float64)

## **`Define the Model`**

In [78]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  # Loss Function
  def loss_function(self, y_pred, y):
    # clamp prediction to avoid log(0)
    epsilon =  1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

**Parameters**

In [79]:
learning_rate = 0.1
epochs = 25

In [80]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [81]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # Loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward Pass
  loss.backward()

  # Prameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print Loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7252708673477173
Epoch: 2, Loss: 0.715641975402832
Epoch: 3, Loss: 0.7092078328132629
Epoch: 4, Loss: 0.7045703530311584
Epoch: 5, Loss: 0.700968325138092
Epoch: 6, Loss: 0.6979949474334717
Epoch: 7, Loss: 0.6954302787780762
Epoch: 8, Loss: 0.6931518912315369
Epoch: 9, Loss: 0.6910879611968994
Epoch: 10, Loss: 0.6891939640045166
Epoch: 11, Loss: 0.6874402761459351
Epoch: 12, Loss: 0.6858064532279968
Epoch: 13, Loss: 0.6842772364616394
Epoch: 14, Loss: 0.6828410625457764
Epoch: 15, Loss: 0.6814886331558228
Epoch: 16, Loss: 0.680212676525116
Epoch: 17, Loss: 0.6790066957473755
Epoch: 18, Loss: 0.6778656244277954
Epoch: 19, Loss: 0.6767846345901489
Epoch: 20, Loss: 0.67576003074646
Epoch: 21, Loss: 0.6747879981994629
Epoch: 22, Loss: 0.673865556716919
Epoch: 23, Loss: 0.672989547252655
Epoch: 24, Loss: 0.6721574068069458
Epoch: 25, Loss: 0.6713666915893555


In [82]:
model.linear.weight

Parameter containing:
tensor([[-0.0307,  0.0747, -0.1097, -0.0177, -0.0496, -0.0014, -0.1678,  0.1075,
         -0.0247, -0.0068, -0.1255, -0.0058, -0.0893,  0.0878,  0.0210, -0.0094,
          0.0649,  0.0496,  0.0962, -0.0020,  0.0378, -0.0579,  0.1229,  0.1167,
          0.0557,  0.0159, -0.0251, -0.0257, -0.0135,  0.0199]],
       requires_grad=True)

**Evaluation**

In [83]:
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float().view(-1, 1)

with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.85).float()
    accuracy = (y_pred == y_test_tensor).float().mean()

print("Accuracy:", accuracy.item())

Accuracy: 0.5877193212509155




1.   Built-in Loss Function
2.   Built-in Optimizer Function



In [85]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # Loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # Clear gradients
  optimizer.zero_grad()

  # Backward Pass
  loss.backward()

  # Prameters Update
  optimizer.step()

  # Print Loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7094045281410217
Epoch: 2, Loss: 0.706574559211731
Epoch: 3, Loss: 0.7039274573326111
Epoch: 4, Loss: 0.7014448642730713
Epoch: 5, Loss: 0.6991117596626282
Epoch: 6, Loss: 0.6969151496887207
Epoch: 7, Loss: 0.6948440670967102
Epoch: 8, Loss: 0.6928892135620117
Epoch: 9, Loss: 0.6910420060157776
Epoch: 10, Loss: 0.6892949342727661
Epoch: 11, Loss: 0.6876416802406311
Epoch: 12, Loss: 0.6860761642456055
Epoch: 13, Loss: 0.6845929026603699
Epoch: 14, Loss: 0.6831871271133423
Epoch: 15, Loss: 0.6818540096282959
Epoch: 16, Loss: 0.6805895566940308
Epoch: 17, Loss: 0.6793897151947021
Epoch: 18, Loss: 0.6782510280609131
Epoch: 19, Loss: 0.6771699786186218
Epoch: 20, Loss: 0.6761435270309448
Epoch: 21, Loss: 0.6751684546470642
Epoch: 22, Loss: 0.6742422580718994
Epoch: 23, Loss: 0.6733621954917908
Epoch: 24, Loss: 0.6725257635116577
Epoch: 25, Loss: 0.6717307567596436


In [87]:
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float().view(-1, 1)

with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()

print("Accuracy:", accuracy.item())

Accuracy: 0.5877193212509155


---
---

## **`Dataset and Dataset Loader`**

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [8]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [7]:
X.shape

(10, 2)

In [9]:
y.shape

(10,)

In [10]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [11]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [12]:
from torch.utils.data import Dataset, DataLoader

In [13]:
class CustomDataset(Dataset):
  def __init__(self,features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [14]:
dataset = CustomDataset(X,y)

In [15]:
len(dataset)

10

In [16]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [18]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [19]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-0.5872, -1.9717],
        [-2.8954,  1.9769]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-1.9629, -0.9923]])
tensor([1, 0])
--------------------------------------------------


---
---
# **Pytorch Training Pipeline Using Dataset and DataLoader Class**

In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [22]:
df.shape

(569, 33)

In [23]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [24]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

**Train-Test_split**

In [25]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

**Scaling**

In [26]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
X_train

array([[-0.57641851,  0.31384008, -0.63420088, ..., -0.64083121,
        -0.33329554, -0.86077291],
       [ 0.15438885, -0.93689715,  0.16421178, ...,  0.38292643,
         0.41990029,  0.02389383],
       [ 0.21974561, -0.53419766,  0.1263356 , ..., -0.55628784,
        -0.61182967, -0.88906006],
       ...,
       [-0.65959984, -1.07665756, -0.59589429, ..., -0.85829556,
        -0.27890722,  1.07051837],
       [ 0.22271637,  0.24040665,  0.17927617, ..., -0.21200843,
        -0.86893809, -1.01552026],
       [ 1.50311463,  0.78049773,  1.52990632, ...,  0.86983365,
         0.48912179,  0.43877203]])

In [28]:
y_train

102    B
89     B
434    B
31     M
337    M
      ..
6      M
523    B
145    B
495    B
198    M
Name: diagnosis, Length: 455, dtype: object

**Label Encoder**

In [29]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

**Numpy arrays to Pytorch tensor**


In [30]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [31]:
X_train_tensor.shape

torch.Size([455, 30])

In [32]:
y_train_tensor.shape

torch.Size([455])

In [33]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [34]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [35]:
train_dataset[10]

(tensor([ 1.9636,  2.8248,  1.8828,  2.3353, -0.1314,  0.1725,  0.6156,  0.9939,
         -0.1498, -0.8644,  3.0951,  0.6951,  2.7453,  4.4748, -0.8201, -0.6075,
         -0.3473, -0.4197, -0.8364, -0.5653,  3.4921,  3.5368,  3.2999,  4.7204,
          0.3297,  0.0448,  0.3283,  0.7931, -0.0465, -0.1175]),
 tensor(1.))

In [36]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

**Define the Model**

In [37]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

**Parameters**

In [38]:
learning_rate = 0.1
epochs = 25

In [39]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

**Training Pipeline**

In [40]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.21957889199256897
Epoch: 2, Loss: 0.17839506268501282
Epoch: 3, Loss: 0.0707283467054367
Epoch: 4, Loss: 0.11682204157114029
Epoch: 5, Loss: 0.09235691279172897
Epoch: 6, Loss: 0.06224387511610985
Epoch: 7, Loss: 0.1641998291015625
Epoch: 8, Loss: 0.1231989711523056
Epoch: 9, Loss: 0.02692079171538353
Epoch: 10, Loss: 0.16799096763134003
Epoch: 11, Loss: 0.11756306141614914
Epoch: 12, Loss: 0.10495976358652115
Epoch: 13, Loss: 0.011077119037508965
Epoch: 14, Loss: 0.25253695249557495
Epoch: 15, Loss: 0.015256251208484173
Epoch: 16, Loss: 0.0014061153633520007
Epoch: 17, Loss: 0.05477959290146828
Epoch: 18, Loss: 0.03294093534350395
Epoch: 19, Loss: 0.025643855333328247
Epoch: 20, Loss: 0.03530869632959366
Epoch: 21, Loss: 0.012289175763726234
Epoch: 22, Loss: 0.0154267568141222
Epoch: 23, Loss: 0.044403377920389175
Epoch: 24, Loss: 0.012397282756865025
Epoch: 25, Loss: 0.0005257914308458567


**Evaluation**

In [41]:
# Model evaluation using test_loader
model.eval()
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9488
