<a href="https://colab.research.google.com/github/Kahkashan2708/Pytorch-code/blob/main/NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import torch
import torch.nn as nn

In [56]:
# Model
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [57]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model
model(features)    # model.forward(features)

tensor([[0.4144],
        [0.4187],
        [0.3953],
        [0.3813],
        [0.4239],
        [0.4697],
        [0.4167],
        [0.4075],
        [0.4002],
        [0.3886]], grad_fn=<SigmoidBackward0>)

In [58]:
model.linear.weight

Parameter containing:
tensor([[-0.1158, -0.3139, -0.3534, -0.2881, -0.1520]], requires_grad=True)

In [59]:
model.linear.bias

Parameter containing:
tensor([0.3275], requires_grad=True)

In [60]:
! pip install torchinfo

In [61]:
from torchinfo import summary
summary(model, inpur_size=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

---

In [62]:
# Model
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [63]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model
model(features)

tensor([[0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077],
        [0.4077]], grad_fn=<SigmoidBackward0>)

In [64]:
model.linear1.weight

Parameter containing:
tensor([[ 0.2622, -0.2283,  0.4065, -0.4420, -0.3278],
        [-0.4357,  0.0228, -0.1094,  0.1190, -0.2577],
        [-0.0964, -0.3835, -0.2896, -0.4331,  0.0149]], requires_grad=True)

In [65]:
model.linear2.weight

Parameter containing:
tensor([[-0.1398, -0.2090, -0.5143]], requires_grad=True)

In [66]:
from torchinfo import summary
summary(model, inpur_size=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

Can we simplify forward pass?

Yes,We will use sequential containers

In [67]:
# Model
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(nn.Linear(num_features, 3),
                                nn.ReLU(),
                                nn.Linear(3,1),
                                nn.Sigmoid() )

  def forward(self, features):
    out = self.network(features)
    return out

---
---

In [68]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [69]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [70]:
df.shape

(569, 33)

In [71]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [72]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

**Train-test Split**

In [73]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

**Scaling**

In [74]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

**Label Encoder**

In [75]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

**Numpy Arrays to pytorch Tensors**

In [76]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [77]:
X_train_tensor

tensor([[ 0.7247, -0.2390,  0.6551,  ..., -0.3327, -0.7877, -1.0234],
        [-0.1551, -1.5658, -0.2385,  ..., -1.4396, -0.9937, -1.1751],
        [-0.0378, -0.0131, -0.1086,  ..., -0.4885, -0.8494, -0.4023],
        ...,
        [ 0.6544,  0.6147,  0.6936,  ..., -0.1170, -0.2329, -0.2106],
        [-0.3134, -0.2390, -0.3030,  ..., -0.7354,  0.5311, -0.5972],
        [ 1.4873,  1.6633,  1.6167,  ...,  1.1544, -0.9224,  0.4741]],
       dtype=torch.float64)

## **`Define the Model`**

In [78]:
import torch.nn as nn
class MySimpleNN(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  # Loss Function
  def loss_function(self, y_pred, y):
    # clamp prediction to avoid log(0)
    epsilon =  1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

Parameters

In [79]:
learning_rate = 0.1
epochs = 25

In [80]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [81]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # Loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward Pass
  loss.backward()

  # Prameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print Loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7252708673477173
Epoch: 2, Loss: 0.715641975402832
Epoch: 3, Loss: 0.7092078328132629
Epoch: 4, Loss: 0.7045703530311584
Epoch: 5, Loss: 0.700968325138092
Epoch: 6, Loss: 0.6979949474334717
Epoch: 7, Loss: 0.6954302787780762
Epoch: 8, Loss: 0.6931518912315369
Epoch: 9, Loss: 0.6910879611968994
Epoch: 10, Loss: 0.6891939640045166
Epoch: 11, Loss: 0.6874402761459351
Epoch: 12, Loss: 0.6858064532279968
Epoch: 13, Loss: 0.6842772364616394
Epoch: 14, Loss: 0.6828410625457764
Epoch: 15, Loss: 0.6814886331558228
Epoch: 16, Loss: 0.680212676525116
Epoch: 17, Loss: 0.6790066957473755
Epoch: 18, Loss: 0.6778656244277954
Epoch: 19, Loss: 0.6767846345901489
Epoch: 20, Loss: 0.67576003074646
Epoch: 21, Loss: 0.6747879981994629
Epoch: 22, Loss: 0.673865556716919
Epoch: 23, Loss: 0.672989547252655
Epoch: 24, Loss: 0.6721574068069458
Epoch: 25, Loss: 0.6713666915893555


In [82]:
model.linear.weight

Parameter containing:
tensor([[-0.0307,  0.0747, -0.1097, -0.0177, -0.0496, -0.0014, -0.1678,  0.1075,
         -0.0247, -0.0068, -0.1255, -0.0058, -0.0893,  0.0878,  0.0210, -0.0094,
          0.0649,  0.0496,  0.0962, -0.0020,  0.0378, -0.0579,  0.1229,  0.1167,
          0.0557,  0.0159, -0.0251, -0.0257, -0.0135,  0.0199]],
       requires_grad=True)

**Evaluation**

In [83]:
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float().view(-1, 1)

with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.85).float()
    accuracy = (y_pred == y_test_tensor).float().mean()

print("Accuracy:", accuracy.item())

Accuracy: 0.5877193212509155




1.   Built-in Loss Function
2.   Built-in Optimizer Function



In [85]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # Loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # Clear gradients
  optimizer.zero_grad()

  # Backward Pass
  loss.backward()

  # Prameters Update
  optimizer.step()

  # Print Loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7094045281410217
Epoch: 2, Loss: 0.706574559211731
Epoch: 3, Loss: 0.7039274573326111
Epoch: 4, Loss: 0.7014448642730713
Epoch: 5, Loss: 0.6991117596626282
Epoch: 6, Loss: 0.6969151496887207
Epoch: 7, Loss: 0.6948440670967102
Epoch: 8, Loss: 0.6928892135620117
Epoch: 9, Loss: 0.6910420060157776
Epoch: 10, Loss: 0.6892949342727661
Epoch: 11, Loss: 0.6876416802406311
Epoch: 12, Loss: 0.6860761642456055
Epoch: 13, Loss: 0.6845929026603699
Epoch: 14, Loss: 0.6831871271133423
Epoch: 15, Loss: 0.6818540096282959
Epoch: 16, Loss: 0.6805895566940308
Epoch: 17, Loss: 0.6793897151947021
Epoch: 18, Loss: 0.6782510280609131
Epoch: 19, Loss: 0.6771699786186218
Epoch: 20, Loss: 0.6761435270309448
Epoch: 21, Loss: 0.6751684546470642
Epoch: 22, Loss: 0.6742422580718994
Epoch: 23, Loss: 0.6733621954917908
Epoch: 24, Loss: 0.6725257635116577
Epoch: 25, Loss: 0.6717307567596436


In [87]:
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float().view(-1, 1)

with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()

print("Accuracy:", accuracy.item())

Accuracy: 0.5877193212509155
